### ISSUE TITLE
/usr/local/lib/node_modules/kludgy/node_modules/zombie/lib/eventloop.js:594             throw error;

### ISSUE THREAD

**Issue by beekman** [mhulse/kludgy#29] opened 2017-10-18 03:54 UTC
kludgy "***api key redacted***" /Users/djbeeker/Desktop/
/usr/local/lib/node_modules/kludgy/node_modules/zombie/lib/eventloop.js:594
            throw error;
            ^

Error: Timeout: did not get to load all resources on this page
    at Timeout.timeout (/usr/local/lib/node_modules/kludgy/node_modules/zombie/lib/eventloop.js:601:38)
    at ontimeout (timers.js:471:11)
    at tryOnTimeout (timers.js:306:5)
    at Timer.listOnTimeout (timers.js:266:5)
Error: Must specify panoID with --id option
    at Promise (/usr/local/lib/node_modules/kludgy/node_modules/extract-streetview/index.js:42:34)
    at parseLocation (/usr/local/lib/node_modules/kludgy/node_modules/extract-streetview/index.js:39:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/kludgy/node_modules/extract-streetview/index.js:34:1)
    at Module._compile (module.js:413:34)
    at Object.devtoolCompileModule [as .js] (/usr/local/lib/node_modules/kludgy/node_modules/devtool/lib/require-hook.js:32:14)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/kludgy/node_modules/devtool/lib/preload.js:78:16)
Error: Format error in file - /Users/djbeeker/Desktop/.jpg

In case this is useful. Probably something to do with my upgrade to High Sierra between now and the last time it was working for me.

**Comment by mhulse** [comment] 2017-10-18 04:04
Hrmmmm, thanks for the report Beeker! I have not upgraded to the High Sierra yet.

Looks like the panoID is not getting passed down the chain for some reason.

Just tested on Sierra:

```bash
$ kludgy "KEY" /Users/mhulse/Desktop/
```

Did not see error... 

I think I will upgrade to High Sierra and see what happens.

Thanks!

**Comment by mhulse** [comment] 2017-10-21 03:43
Just upgraded to High Sierra... Unfortunately, I could not reproduce. Wondering if it was a network burp?

**Comment by mhulse** [comment] 2018-01-06 07:06
I'm now getting this as well on both my laptop and work computer. Wondering if it's a dependency version/node version thing. Closing in favor of #31 (and #30).

Thanks for the report @beekman!

**Closed as completed by mhulse** 2018-01-06 07:06 UTC
Labels: bug, duplicate
